/**
 * Wire protocol between parallel_write and its content-generation workers.
 *
 * Everything here is pure string handling with no I/O, no provider calls and no Electron
 * dependency, so the whole protocol (prompt shape + parser) is unit-testable on its own. That
 * matters more than usual: a parser bug here doesn't throw, it silently produces *plausible wrong
 * file content*, which is the one failure mode this feature must never have.
 *
 * WHY A DELIMITED ENVELOPE RATHER THAN JSON
 * ----------------------------------------
 * Workers emit source code. JSON-encoding source inflates it (every newline, quote and backslash
 * becomes an escape) and, worse, a generation cut off by the output-token limit yields a JSON
 * document that cannot be parsed *at all* — losing every file in the batch, including the ones
 * that finished. A line-delimited envelope degrades gracefully: completed blocks parse, and the
 * one that got cut off is detectable precisely because its closing sentinel never arrived.
 *
 * WHY A PER-CALL NONCE
 * --------------------
 * Fixed sentinels break the first time a worker writes code *about* this protocol (which this
 * repo's own agent does constantly). An unguessable per-call nonce embedded in every sentinel
 * makes collision with generated content impossible in practice, so the parser can trust a
 * sentinel line without heuristics.
 */

import { randomBytes } from 'node:crypto'
import { toLf } from './eol'

/** Hex chars in a call's sentinel nonce. 12 hex chars (~48 bits) is far past the point where a
 *  model could emit a colliding line by chance, and short enough to stay readable in a prompt. */
const NONCE_HEX_CHARS = 12

export function makeNonce(): string {
  return randomBytes(Math.ceil(NONCE_HEX_CHARS / 2))
    .toString('hex')
    .slice(0, NONCE_HEX_CHARS)
}

export interface ParsedFileBlock {
  kind: 'file'
  path: string
  content: string
}

export interface ParsedEditBlock {
  kind: 'edit'
  path: string
  oldString: string
  newString: string
}

export type ParsedBlock = ParsedFileBlock | ParsedEditBlock

export type ParseFailureReason =
  /** a block was opened but its closing sentinel never arrived — the generation was cut off */
  | 'truncated'
  /** the worker declined the job and said why (its `ERROR:` escape hatch) */
  | 'worker_error'
  /** no blocks at all, and no explicit error either */
  | 'empty'
  /** sentinels arrived in an impossible order (e.g. NEW before OLD) */
  | 'malformed'

export type ParseResult =
  | { ok: true; blocks: ParsedBlock[] }
  | { ok: false; reason: ParseFailureReason; summary: string }

interface Sentinels {
  fileOpen: RegExp
  editOpen: RegExp
  oldMark: string
  newMark: string
  endMark: string
}

function sentinelsFor(nonce: string): Sentinels {
  // The nonce is generated by makeNonce() (hex only), so it needs no regex escaping. Anchored at
  // both ends so a sentinel is only recognized as an entire line, never mid-content.
  return {
    fileOpen: new RegExp(`^<<<KLENNY-FILE:${nonce} path=(.+)>>>$`),
    editOpen: new RegExp(`^<<<KLENNY-EDIT:${nonce} path=(.+)>>>$`),
    oldMark: `<<<OLD:${nonce}>>>`,
    newMark: `<<<NEW:${nonce}>>>`,
    endMark: `<<<KLENNY-END:${nonce}>>>`
  }
}

/** The protocol spec handed to every worker. Uses the real nonce so the worker copies it verbatim
 *  rather than having to substitute a placeholder. */
function protocolSpec(nonce: string): string {
  return `Reply with ONLY the delimited blocks below. No preamble, no explanation, no commentary,
and no markdown code fences wrapping them.

To write a file's complete contents:
<<<KLENNY-FILE:${nonce} path=RELATIVE/PATH>>>
...the file's entire content...
<<<KLENNY-END:${nonce}>>>

To change part of a file that already exists:
<<<KLENNY-EDIT:${nonce} path=RELATIVE/PATH>>>
<<<OLD:${nonce}>>>
...text that currently exists in the file, copied exactly...
<<<NEW:${nonce}>>>
...text to replace it with...
<<<KLENNY-END:${nonce}>>>

Rules:
- Every sentinel line must appear alone on its own line, byte-for-byte as shown above, with no
  leading or trailing whitespace and nothing else on the line.
- Emit exactly one block per file you were asked to produce. Never emit a block for a file you
  were not asked about.
- You may emit several EDIT blocks for the same file; they are applied in the order given, and a
  later block's OLD text may match text an earlier one produced.
- OLD text must be copied byte-for-byte from the file content provided to you, and must occur
  exactly once in that file. Include enough surrounding lines to make it unique.
- Prefer EDIT blocks over rewriting a whole file: they are cheaper and safer. Use a FILE block for
  a brand-new file, or when genuinely replacing the entire contents.
- Always emit LF line endings. The harness restores each target file's own convention on write.
- If you cannot do the job correctly — missing context, an interface you were not shown, an
  ambiguous instruction — emit NO blocks at all and reply with a single line beginning
  "ERROR: " explaining exactly what you needed. Never guess at an interface, a file path, or the
  contents of a file you were not given. A loud failure is cheap; a confidently wrong file is not.`
}

export interface WorkerContextFile {
  path: string
  content: string
}

/**
 * Builds the worker system prompt — the part that is BYTE-IDENTICAL for every job in a batch, and
 * therefore the only part that can serve as a cacheable prefix.
 *
 * Nothing job-specific may ever be added here. If it varies per job it belongs in
 * buildWorkerUserContent below, or the shared prefix stops being shared and the entire caching
 * strategy (and the priming gate in openrouter/caching.ts) is silently defeated.
 *
 * Note what is deliberately absent: tool schemas, conversation history, memory notes, skills and
 * subagent catalogs. A worker transcribes content from an instruction; it does not plan, call
 * tools, or need to know anything about the wider session. Omitting all of it is the single
 * largest cost saving in the feature.
 */
export function buildWorkerSystemPrompt(opts: {
  nonce: string
  sharedContext?: string
  contextFiles: WorkerContextFile[]
}): string {
  const sections: string[] = [
    'You are a file-content generation worker. You produce file contents and nothing else.',
    protocolSpec(opts.nonce)
  ]

  if (opts.sharedContext && opts.sharedContext.trim()) {
    sections.push(`Project conventions and shared context that apply to your output:\n${opts.sharedContext.trim()}`)
  }

  if (opts.contextFiles.length > 0) {
    const files = opts.contextFiles
      .map((f) => `--- ${f.path} ---\n${f.content}`)
      .join('\n\n')
    sections.push(
      `Reference files, provided so you can match existing style and interfaces. These are context only — do NOT emit blocks for them unless your own instructions name them as targets:\n\n${files}`
    )
  }

  return sections.join('\n\n')
}

export interface WorkerJobSpec {
  kind: 'write' | 'edit'
  /** files this job is responsible for producing */
  paths: string[]
  instructions: string
  /** current contents of each target, for edit jobs */
  targets?: WorkerContextFile[]
}

/** Builds the per-job user message: everything that differs between workers. */
export function buildWorkerUserContent(job: WorkerJobSpec, nonce: string): string {
  const sections: string[] = []

  if (job.kind === 'write') {
    sections.push(
      `Produce the complete contents of ${job.paths.length === 1 ? 'this file' : 'these files'} using KLENNY-FILE blocks:\n${job.paths
        .map((p) => `- ${p}`)
        .join('\n')}`
    )
  } else {
    sections.push(
      `Modify ${job.paths.length === 1 ? 'this file' : 'these files'} using KLENNY-EDIT blocks:\n${job.paths.map((p) => `- ${p}`).join('\n')}`
    )
  }

  sections.push(`Instructions:\n${job.instructions.trim()}`)

  if (job.targets && job.targets.length > 0) {
    const targets = job.targets.map((t) => `--- ${t.path} (current contents) ---\n${t.content}`).join('\n\n')
    sections.push(`Current contents of your target ${job.targets.length === 1 ? 'file' : 'files'}:\n\n${targets}`)
  }

  sections.push(`Emit only KLENNY blocks using the nonce ${nonce}, nothing else.`)
  return sections.join('\n\n')
}

function stripBom(s: string): string {
  return s.charCodeAt(0) === 0xfeff ? s.slice(1) : s
}

/** A fence a worker may have wrapped its output in despite being told not to. Only ever skipped
 *  while between blocks, so a fence inside a file's content is preserved untouched. */
function isStrayFence(line: string): boolean {
  return /^```[A-Za-z0-9+#.-]*$/.test(line.trim())
}

/**
 * Parses a worker's raw output into applicable blocks.
 *
 * Line-anchored by construction: a sentinel is only honoured as an entire line, so content that
 * merely mentions one is never mistaken for a delimiter. Never throws — every malformed shape
 * comes back as a typed failure the caller can report and, where appropriate, retry.
 */
export function parseWorkerOutput(raw: string, nonce: string): ParseResult {
  const s = sentinelsFor(nonce)
  // CR is stripped per-line rather than globally so a worker emitting CRLF parses identically to
  // one emitting LF; the harness re-applies each target file's real convention when writing.
  const lines = toLf(stripBom(raw)).split('\n')

  const blocks: ParsedBlock[] = []
  type State =
    | { at: 'idle' }
    | { at: 'file'; path: string; buf: string[] }
    | { at: 'edit-old'; path: string; buf: string[]; sawOld: boolean }
    | { at: 'edit-new'; path: string; oldString: string; buf: string[] }
  let state: State = { at: 'idle' }
  let workerError: string | undefined

  for (const line of lines) {
    if (state.at === 'idle') {
      const fileMatch = s.fileOpen.exec(line)
      if (fileMatch) {
        state = { at: 'file', path: fileMatch[1].trim(), buf: [] }
        continue
      }
      const editMatch = s.editOpen.exec(line)
      if (editMatch) {
        state = { at: 'edit-old', path: editMatch[1].trim(), buf: [], sawOld: false }
        continue
      }
      if (line === s.oldMark || line === s.newMark || line === s.endMark) {
        return {
          ok: false,
          reason: 'malformed',
          summary: `Found "${line.trim()}" with no open block before it — sentinels arrived out of order.`
        }
      }
      // Only recognized between blocks, so a file whose content happens to start a line with
      // "ERROR: " is never misread as the worker refusing the job.
      if (!workerError && /^ERROR:/i.test(line.trim())) workerError = line.trim().replace(/^ERROR:\s*/i, '')
      // Anything else between blocks (blank lines, a stray fence, leftover prose) is ignored:
      // the blocks are the contract, and discarded chatter is strictly safer than failing a job
      // whose actual content arrived intact.
      continue
    }

    if (state.at === 'file') {
      if (line === s.endMark) {
        blocks.push({ kind: 'file', path: state.path, content: state.buf.join('\n') })
        state = { at: 'idle' }
        continue
      }
      state.buf.push(line)
      continue
    }

    if (state.at === 'edit-old') {
      if (line === s.newMark) {
        state = { at: 'edit-new', path: state.path, oldString: state.buf.join('\n'), buf: [] }
        continue
      }
      if (line === s.endMark) {
        return {
          ok: false,
          reason: 'malformed',
          summary: `Edit block for ${state.path} ended without a <<<NEW:${nonce}>>> section.`
        }
      }
      if (!state.sawOld) {
        // The OLD marker is expected immediately after the EDIT opener. Tolerate blank lines and a
        // stray fence before it; anything substantive means the worker skipped the marker, in
        // which case treat this line as the start of the OLD text rather than discarding a job
        // whose content otherwise arrived intact.
        if (line === s.oldMark) {
          state.sawOld = true
          continue
        }
        if (line.trim() === '' || isStrayFence(line)) continue
        state.sawOld = true
        state.buf.push(line)
        continue
      }
      state.buf.push(line)
      continue
    }

    // state.at === 'edit-new'
    if (line === s.endMark) {
      blocks.push({ kind: 'edit', path: state.path, oldString: state.oldString, newString: state.buf.join('\n') })
      state = { at: 'idle' }
      continue
    }
    state.buf.push(line)
  }

  if (state.at !== 'idle') {
    return {
      ok: false,
      reason: 'truncated',
      summary: `Output ended while still inside a block for ${state.path} — the closing <<<KLENNY-END:${nonce}>>> never arrived, so the generation was cut off. Nothing was applied.`
    }
  }

  if (blocks.length === 0) {
    return workerError
      ? { ok: false, reason: 'worker_error', summary: `Worker declined the job: ${workerError}` }
      : { ok: false, reason: 'empty', summary: 'Worker produced no KLENNY blocks and no explicit error.' }
  }

  return { ok: true, blocks }
}

/** Retry note sent to a worker whose first attempt was cut off mid-block.
 *
 *  Deliberately *informed* rather than a bare "try again": it states what actually happened (no
 *  file was created, nothing ran), and points at the cheapest way to fit inside the budget —
 *  which for this protocol is emitting edit fragments instead of whole files. Same reasoning as
 *  the truncation-retry note in turnControl.ts. */
export function buildTruncationRetryNote(nonce: string): string {
  return `Your previous reply was cut off before the closing <<<KLENNY-END:${nonce}>>> sentinel arrived, so NOTHING was applied — no file was created or modified.

Emit the blocks again, and make them fit this time:
- Skip all preamble and commentary; spend the entire budget on block content.
- Prefer KLENNY-EDIT blocks with the smallest unique OLD fragment over whole-file KLENNY-FILE blocks — a fragment costs a fraction of the tokens of a full file.
- If you were asked for several files and cannot fit them all, emit complete blocks for as many as fit and stop at a block boundary. A complete block is applicable; a truncated one is discarded entirely.`
}
