import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import type { ChatMessage, ChecklistBlock, MessageVerification, ToolCallBlock } from '@shared/types'
import { DEFAULT_BRAND_NAME } from '@shared/types'
import { ThinkingBlock } from './ThinkingBlock'
import { ToolCallCard } from './ToolCallCard'
import { DiffViewer } from './DiffViewer'
import { ChecklistWidget } from './ChecklistWidget'
import klennyGif from '../assets/klenny.gif'
import { useAppStore } from '../store/useAppStore'

/** Fabrication-guard verdict banner. Deliberately states what the harness actually checked rather
 *  than a bare "unverified" label, so the user can judge the claim themselves — the findings are
 *  advisory evidence, never proof that the underlying work is wrong. */
function VerificationBadge({ verification }: { verification: MessageVerification }) {
  const disputed = verification.status === 'disputed'
  return (
    <div
      className={`mb-2 rounded px-2 py-1.5 text-xs border ${
        disputed ? 'bg-red-400/10 border-red-400/40 text-red-300' : 'bg-amber-400/10 border-amber-400/30 text-amber-300'
      }`}
    >
      <div className="font-medium">
        {disputed
          ? '⚠ Disputed — claims below contradict the harness’s execution records'
          : '⚠ Unverified narration — claims below could not be corroborated'}
      </div>
      <ul className="mt-1 space-y-0.5 list-disc list-inside">
        {verification.findings.map((f, i) => (
          <li key={i}>
            <span className="opacity-70">[{f.code}]</span> {f.detail}
            {f.excerpt && <span className="opacity-60 italic"> — “{f.excerpt}”</span>}
          </li>
        ))}
      </ul>
    </div>
  )
}

export function MessageBubble({ message }: { message: ChatMessage }) {
  // Audit notes ride on role:'user' purely because of how toORMessages() works — they are written
  // by the harness, not the user, so they must never be styled as something the user said.
  const isAuditNote = Boolean(message.isAuditNote)
  const isUser = message.role === 'user' && !isAuditNote
  const isEmptyAssistant = message.role !== 'user' && message.blocks.length === 0
  const customRunningGifUrl = useAppStore((s) => s.customRunningGifUrl)
  const brandName = useAppStore((s) => s.settings?.brandName) || DEFAULT_BRAND_NAME

  if (isEmptyAssistant) {
    return (
      <div className="flex justify-start">
        <img
          src={customRunningGifUrl ?? klennyGif}
          alt={`${brandName} is working…`}
          className="h-12 w-12 rounded-md object-cover"
        />
      </div>
    )
  }

  // A message whose sole block is a checklist is the live plan-progress widget (created by
  // approvePlan, mutated in place by update_checklist) — render it standalone, not as a chat
  // bubble.
  if (!isUser && message.blocks.length === 1 && message.blocks[0].type === 'checklist') {
    return (
      <div className="w-full">
        <ChecklistWidget block={message.blocks[0] as ChecklistBlock} />
      </div>
    )
  }

  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div
        className={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${
          isAuditNote
            ? 'bg-amber-400/5 border border-amber-400/40 border-dashed'
            : isUser
              ? 'bg-klenny-accent/20 border border-klenny-accent/30'
              : message.verification?.status === 'disputed'
                ? 'bg-klenny-panel2 border border-red-400/50'
                : message.verification?.status === 'warned'
                  ? 'bg-klenny-panel2 border border-amber-400/40'
                  : 'bg-klenny-panel2 border border-klenny-border'
        }`}
      >
        {message.isCompactionSummary && (
          <div className="text-xs text-klenny-muted mb-2">Compaction summary</div>
        )}
        {isAuditNote && (
          <div className="text-xs font-medium text-amber-300 mb-2">
            🛡 Fabrication guard — automatic audit note (generated by {brandName}, not by you)
          </div>
        )}
        {message.verification && <VerificationBadge verification={message.verification} />}
        {message.blocks.map((block, i) => {
          if (block.type === 'text') {
            return (
              <div key={i} className="markdown prose prose-invert prose-sm max-w-none">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{block.text}</ReactMarkdown>
              </div>
            )
          }
          if (block.type === 'thinking') return <ThinkingBlock key={i} text={block.text} />
          if (block.type === 'image') {
            return <img key={i} src={block.dataUrl} alt="uploaded" className="max-h-48 rounded mt-2" />
          }
          if (block.type === 'document') {
            return (
              <div
                key={i}
                className="flex items-center gap-2 mt-2 px-3 py-2 rounded border border-klenny-border bg-klenny-panel text-xs"
                title={block.filename}
              >
                <span className="text-base">📄</span>
                <span className="truncate">{block.filename}</span>
                {block.truncated && <span className="text-klenny-muted shrink-0">(truncated)</span>}
              </div>
            )
          }
          if (block.type === 'tool_call') {
            const tc = block as ToolCallBlock
            // update_checklist mutates the standalone checklist widget in place; showing a tool
            // card for it too would be redundant noise in the transcript.
            if (tc.toolName === 'update_checklist') return null
            const diff = (tc.result?.data as { diff?: string })?.diff
            return (
              <div key={i} className="mt-2 space-y-2">
                <ToolCallCard block={tc} />
                {diff && <DiffViewer diff={diff} />}
              </div>
            )
          }
          return null
        })}
        {(message.usage || message.reasoningEffort) && (
          <div className="text-[10px] text-klenny-muted mt-2">
            {message.usage && (
              <>
                {message.usage.completionTokens} completion tokens · ${message.usage.costUsd.toFixed(4)}
                {message.usage.cachedTokens > 0 && (
                  <span className="text-green-400">
                    {' '}
                    · {message.usage.cachedTokens} cached (saved ${Math.max(message.usage.cacheSavingsUsd, 0).toFixed(4)})
                  </span>
                )}
                {message.usage.cacheWriteTokens > 0 && (
                  <span className="text-klenny-muted"> · {message.usage.cacheWriteTokens} cache-write</span>
                )}
              </>
            )}
            {message.reasoningEffort && <span> · reasoning: {message.reasoningEffort}</span>}
          </div>
        )}
      </div>
    </div>
  )
}
