import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { parseFrontmatterSafe, stringifyFrontmatter } from '../frontmatter'
import type { SubagentTypeSummary, ToolName } from '@shared/types'
import { getWorkspace } from '../../workspace'
import { globalKlennyDir } from '../../dataDir'

const BUILT_IN: SubagentTypeSummary[] = [
  {
    name: 'general-purpose',
    description: 'General-purpose agent for multi-step tasks and research.',
    tools: 'all',
    builtIn: true
  },
  {
    name: 'explore',
    description: 'Fast read-only codebase exploration. Use for searching files and understanding structure.',
    tools: [
      'read_file',
      'grep',
      'glob',
      'web_search',
      'fetch_url',
      'read_memory',
      'list_memory',
      'codebase_search',
      'list_projects'
    ],
    builtIn: true
  },
  {
    name: 'plan-checker',
    description: 'Review a plan for gaps, risks, and missing steps before implementation.',
    tools: [
      'read_file',
      'grep',
      'glob',
      'web_search',
      'fetch_url',
      'read_memory',
      'list_memory',
      'codebase_search',
      'list_projects'
    ],
    builtIn: true
  }
]

export async function listSubagentTypes(): Promise<SubagentTypeSummary[]> {
  const custom: SubagentTypeSummary[] = []
  const ws = getWorkspace()
  if (ws) custom.push(...(await scanAgents(join(ws, '.klenny', 'agents'), 'project')))
  custom.push(...(await scanAgents(join(globalKlennyDir(), 'agents'), 'global')))
  return [...BUILT_IN, ...custom]
}

async function scanAgents(dir: string, scope: 'project' | 'global'): Promise<SubagentTypeSummary[]> {
  const out: SubagentTypeSummary[] = []
  try {
    const files = await readdir(dir)
    for (const file of files) {
      if (!file.endsWith('.md')) continue
      const path = join(dir, file)
      // Per-file try/catch: one unreadable definition must not abort the whole directory scan and
      // take every other custom subagent down with it.
      try {
        const raw = await readFile(path, 'utf8')
        // Safe parse — same free-text-description YAML hazard as skills (see frontmatter.ts).
        const { data, content } = parseFrontmatterSafe(raw)
        // Explicit annotation: without it the fallback array literal widens the union to
        // `string[] | 'all'`, which isn't assignable to SubagentTypeSummary['tools'].
        const tools: ToolName[] | 'all' =
          data.tools === 'all' ? 'all' : Array.isArray(data.tools) ? (data.tools as ToolName[]) : ['read_file', 'grep', 'glob']
        out.push({
          name: String(data.name ?? file.replace(/\.md$/, '')),
          description: String(data.description ?? ''),
          tools,
          model: data.model ? String(data.model) : undefined,
          builtIn: false,
          scope,
          path,
          body: content.trim()
        })
      } catch {
        // skip just this file
      }
    }
  } catch {
    // none
  }
  return out
}

export async function writeSubagentType(
  name: string,
  scope: 'project' | 'global',
  description: string,
  tools: string[] | 'all',
  model: string | undefined,
  body: string
): Promise<void> {
  if (BUILT_IN.some((b) => b.name === name)) {
    throw new Error(`"${name}" is a built-in subagent name and cannot be overwritten`)
  }
  let dir: string
  if (scope === 'global') {
    dir = join(globalKlennyDir(), 'agents')
  } else {
    const ws = getWorkspace()
    if (!ws) throw new Error('No workspace open — cannot write a project-scoped subagent')
    dir = join(ws, '.klenny', 'agents')
  }
  await mkdir(dir, { recursive: true })
  // Same escaping requirement as writeSkill — `description` is model-supplied free text, so the
  // YAML has to be generated by a serializer rather than interpolated. `model: undefined` is
  // omitted by stringifyFrontmatter, preserving the old conditional-line behavior.
  await writeFile(join(dir, `${name}.md`), stringifyFrontmatter({ name, description, tools, model }, body), 'utf8')
}

export function getBuiltInSubagent(name: string): SubagentTypeSummary | undefined {
  return BUILT_IN.find((b) => b.name === name)
}

export async function getSubagentType(name: string): Promise<SubagentTypeSummary | undefined> {
  const all = await listSubagentTypes()
  return all.find((a) => a.name === name)
}

export function subagentsCatalog(types: SubagentTypeSummary[]): string {
  return types.map((t) => `- ${t.name}: ${t.description}`).join('\n')
}
